GRAPHQL http://localhost:8080/graphql

{
    __schema {
        queryType {
            fields {
                name
                deprecationReason
                description
                isDeprecated
            }
        }
    }
}

### Get book by id
GRAPHQL http://localhost:8080/graphql

{
    bookById (id: "book-3") {
        name
        author {
            firstName (min: 3, max: 10)
            lastName
        }
        price
    }
}

